openapi: 3.0.3
info:
    title: Chatbook Microservices
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for chatbook-microservices
paths:
    /api/v1/auth/login:
        post:
            tags:
                - auth
            summary: login auth
            operationId: auth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: Provident harum similique saepe fuga assumenda.
                            password: Sequi libero et qui soluta error.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Et delectus qui.
                                id: Quas voluptas ducimus perferendis assumenda eum officiis.
                                refresh_token: Sed quia eveniet sit.
                                role: Ut blanditiis qui.
                                token: Veniam tempore voluptate sunt.
                "404":
                    description: 'WrongCredentials: Email and/or password don''t match'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/v1/auth/refresh-token:
        post:
            tags:
                - auth
            summary: refreshToken auth
            operationId: auth#refreshToken
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshTokenRequestBody'
                        example:
                            email: Assumenda autem quo aut.
                            refreshToken: Reprehenderit totam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Quibusdam voluptatum voluptatum vitae.
                                id: Sit veniam delectus.
                                refresh_token: Qui vel voluptas aperiam quae.
                                role: Explicabo omnis nulla.
                                token: Qui rerum quidem eum id eveniet.
    /api/v1/info:
        get:
            tags:
                - info
            summary: getInfo info
            operationId: info#getInfo
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Amet ut nihil consequuntur odio.
    /api/v1/users:
        get:
            tags:
                - user
            summary: getUserProfile user
            operationId: user#getUserProfile
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserProfileResponse'
                            example:
                                email: Cum eum molestiae sit enim non.
                                firstName: Maxime molestiae.
                                friendsList:
                                    - email: Natus quisquam.
                                      firstName: Illo omnis nesciunt minus sed.
                                      id: 2306687740220369761
                                      lastName: Inventore quisquam.
                                    - email: Natus quisquam.
                                      firstName: Illo omnis nesciunt minus sed.
                                      id: 2306687740220369761
                                      lastName: Inventore quisquam.
                                id: 6938822483663079921
                                lastName: Dolorum rerum.
    /api/v1/users/profile:
        put:
            tags:
                - user
            summary: updateProfileNames user
            operationId: user#updateProfileNames
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateProfileNamesRequestBody'
                        example:
                            firstName: Quibusdam qui.
                            lastName: Tempora perspiciatis ut ut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Optio a.
    /api/v1/users/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            confirmedPassword: Magnam facilis incidunt occaecati consequatur ullam.
                            email: Ducimus asperiores sunt.
                            firstName: Qui impedit tempore sunt optio.
                            lastName: Quisquam eos vitae velit quis.
                            password: Adipisci qui suscipit ut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Quo et.
                "409":
                    description: 'UnmatchingPassowrds: Provided passwords are not the same'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Friend:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Ipsam vel placeat laborum.
                firstName:
                    type: string
                    description: First name
                    example: Et minima incidunt delectus cumque.
                id:
                    type: integer
                    description: User ID
                    example: 18871539287640466
                    format: int64
                lastName:
                    type: string
                    description: Last name
                    example: Et quo animi.
            example:
                email: Reiciendis ex possimus eius accusantium error.
                firstName: Commodi ut autem nam voluptatem.
                id: 7069237682194292264
                lastName: Autem dolorem ipsum.
            required:
                - id
                - email
                - firstName
                - lastName
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Quasi eum dignissimos excepturi.
                password:
                    type: string
                    description: User password
                    example: Ut harum.
            example:
                email: Quaerat iure quod ut voluptate.
                password: Quis eligendi ullam quasi enim laudantium aliquam.
            required:
                - email
                - password
        LoginResponse:
            type: object
            properties:
                email:
                    type: string
                    description: User's email
                    example: Rerum soluta ut deleniti esse.
                id:
                    type: string
                    description: User account's ID
                    example: Error veritatis.
                refresh_token:
                    type: string
                    description: Refresh token
                    example: Magnam totam dolorem.
                role:
                    type: string
                    description: User's role
                    example: Eaque vel.
                token:
                    type: string
                    description: JWT Token
                    example: Quod at aspernatur et repellendus earum.
            example:
                email: Doloremque maxime molestiae natus voluptatem.
                id: Aliquam beatae ipsam aut.
                refresh_token: Qui quasi rerum fugit cum.
                role: Ut doloremque qui voluptatem sed odit.
                token: Omnis ut quod quia beatae magni consequatur.
            required:
                - email
                - token
                - refresh_token
                - role
        OperationStatusResponse:
            type: object
            properties:
                message:
                    type: string
                    description: Operation status
                    example: Optio error est ut velit.
            example:
                message: Numquam molestiae dolorem.
            required:
                - message
        RefreshTokenRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Et ratione perspiciatis.
                refreshToken:
                    type: string
                    description: Refresh token
                    example: Quia sapiente qui.
            example:
                email: Aut quia minus dolores.
                refreshToken: Excepturi dolore blanditiis ut.
            required:
                - email
                - refreshToken
        RegisterRequestBody:
            type: object
            properties:
                confirmedPassword:
                    type: string
                    description: Confirmed password of the user
                    example: Sit perferendis sapiente minima.
                email:
                    type: string
                    description: User email
                    example: Aliquid debitis amet officiis dicta ea.
                firstName:
                    type: string
                    description: User first name
                    example: Voluptate veniam incidunt inventore illum.
                lastName:
                    type: string
                    description: User last name
                    example: Delectus possimus nam accusamus.
                password:
                    type: string
                    description: User password
                    example: Molestiae omnis.
            example:
                confirmedPassword: Aliquid provident est illo officiis.
                email: Voluptatem amet fugit dolores sequi.
                firstName: Nulla sed.
                lastName: Minima error ad veniam pariatur qui.
                password: Dolorem dolorem et pariatur voluptas.
            required:
                - email
                - password
                - confirmedPassword
                - firstName
                - lastName
        UpdateProfileNamesRequestBody:
            type: object
            properties:
                firstName:
                    type: string
                    description: Updated user first name
                    example: Quia ab est repellendus exercitationem aut delectus.
                lastName:
                    type: string
                    description: Updated user last name
                    example: Ex repellendus.
            example:
                firstName: Sapiente nostrum minima reiciendis.
                lastName: Qui beatae deserunt nihil qui recusandae hic.
            required:
                - firstName
                - lastName
        UserProfileResponse:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Quis blanditiis rem est et molestias.
                firstName:
                    type: string
                    description: First name
                    example: Vitae est.
                friendsList:
                    type: array
                    items:
                        $ref: '#/components/schemas/Friend'
                    description: Friendslist
                    example:
                        - email: Natus quisquam.
                          firstName: Illo omnis nesciunt minus sed.
                          id: 2306687740220369761
                          lastName: Inventore quisquam.
                        - email: Natus quisquam.
                          firstName: Illo omnis nesciunt minus sed.
                          id: 2306687740220369761
                          lastName: Inventore quisquam.
                id:
                    type: integer
                    description: User ID
                    example: 6090277619242191338
                    format: int64
                lastName:
                    type: string
                    description: Last name
                    example: Culpa at itaque ad.
            example:
                email: Deleniti sit ipsam qui.
                firstName: Repellendus alias corporis mollitia neque consequuntur.
                friendsList:
                    - email: Natus quisquam.
                      firstName: Illo omnis nesciunt minus sed.
                      id: 2306687740220369761
                      lastName: Inventore quisquam.
                    - email: Natus quisquam.
                      firstName: Illo omnis nesciunt minus sed.
                      id: 2306687740220369761
                      lastName: Inventore quisquam.
                    - email: Natus quisquam.
                      firstName: Illo omnis nesciunt minus sed.
                      id: 2306687740220369761
                      lastName: Inventore quisquam.
                id: 683379816533013218
                lastName: Illum placeat autem.
            required:
                - id
                - email
                - firstName
                - lastName
                - friendsList
tags:
    - name: auth
      description: Authentication service is responsible for handling user data and requests
    - name: info
      description: Application info
    - name: user
      description: User service is responsible for handling user data and requests
