openapi: 3.0.3
info:
    title: Chatbook Microservices
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for chatbook-microservices
paths:
    /api/user-management/v1/auth/login:
        post:
            tags:
                - auth
            summary: login auth
            operationId: auth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: Sed quia eveniet sit.
                            password: Ut blanditiis qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Quas voluptas ducimus perferendis assumenda eum officiis.
                                id: Ducimus asperiores sunt.
                                refresh_token: Qui impedit tempore sunt optio.
                                role: Quisquam eos vitae velit quis.
                                token: Amet ut nihil consequuntur odio.
                "404":
                    description: 'WrongCredentials: Email and/or password don''t match'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user-management/v1/auth/refresh-token:
        post:
            tags:
                - auth
            summary: refreshToken auth
            operationId: auth#refreshToken
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshTokenRequestBody'
                        example:
                            email: Qui vel voluptas aperiam quae.
                            refreshToken: Explicabo omnis nulla.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Sit veniam delectus.
                                id: Veniam tempore voluptate sunt.
                                refresh_token: Sequi libero et qui soluta error.
                                role: Et delectus qui.
                                token: Provident harum similique saepe fuga assumenda.
    /api/user-management/v1/info:
        get:
            tags:
                - info
            summary: getInfo info
            operationId: info#getInfo
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Adipisci qui suscipit ut.
    /api/user-management/v1/users/friend/{id}:
        post:
            tags:
                - user
            summary: addFriend user
            operationId: user#addFriend
            parameters:
                - name: id
                  in: path
                  description: User ID to add
                  required: true
                  schema:
                    type: string
                    description: User ID to add
                    example: Non dolor earum unde.
                  example: Sed numquam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Eum ullam eveniet temporibus quis dolore mollitia.
    /api/user-management/v1/users/friends/{id}:
        delete:
            tags:
                - user
            summary: removeFriend user
            operationId: user#removeFriend
            parameters:
                - name: id
                  in: path
                  description: User ID to delete
                  required: true
                  schema:
                    type: string
                    description: User ID to delete
                    example: Voluptatem incidunt eum reiciendis molestiae quasi impedit.
                  example: Qui officia rerum nulla cum magnam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Vel id doloremque et error.
    /api/user-management/v1/users/profile:
        get:
            tags:
                - user
            summary: getProfile user
            operationId: user#getProfile
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserProfileResponse'
                            example:
                                email: Optio a.
                                firstName: Possimus ad.
                                friendsList:
                                    - email: Dolorum rerum.
                                      firstName: Dolores quibusdam.
                                      id: Maxime molestiae.
                                      lastName: Labore tempora.
                                    - email: Dolorum rerum.
                                      firstName: Dolores quibusdam.
                                      id: Maxime molestiae.
                                      lastName: Labore tempora.
                                    - email: Dolorum rerum.
                                      firstName: Dolores quibusdam.
                                      id: Maxime molestiae.
                                      lastName: Labore tempora.
                                    - email: Dolorum rerum.
                                      firstName: Dolores quibusdam.
                                      id: Maxime molestiae.
                                      lastName: Labore tempora.
                                id: Ut ut.
                                lastName: Quasi quas.
        put:
            tags:
                - user
            summary: updateProfileNames user
            operationId: user#updateProfileNames
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateProfileNamesRequestBody'
                        example:
                            firstName: Quia molestias aut dolores soluta quia recusandae.
                            lastName: Omnis commodi qui quis et inventore.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Officia ipsum consequatur quas velit et.
    /api/user-management/v1/users/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            confirmedPassword: Inventore quisquam.
                            email: Veritatis natus quisquam.
                            firstName: Magnam facilis incidunt occaecati consequatur ullam.
                            lastName: Quo et.
                            password: Illo omnis nesciunt minus sed.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: A cum eum molestiae sit enim non.
                "409":
                    description: 'UnmatchingPassowrds: Provided passwords are not the same'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Friend:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Voluptates nesciunt rerum beatae praesentium accusantium blanditiis.
                firstName:
                    type: string
                    description: First name
                    example: Et officia quia saepe quia dolore nemo.
                id:
                    type: string
                    description: User ID
                    example: Facere consequuntur.
                lastName:
                    type: string
                    description: Last name
                    example: Iusto aliquam nihil dolorum et dicta tempore.
            example:
                email: Nemo quos consequuntur laborum ut officiis commodi.
                firstName: Dolorem ut fuga deleniti id provident molestiae.
                id: Suscipit inventore sint aut est hic.
                lastName: Qui reprehenderit ut.
            required:
                - id
                - email
                - firstName
                - lastName
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Facilis quis blanditiis rem.
                password:
                    type: string
                    description: User password
                    example: Et molestias ducimus.
            example:
                email: Est repellat culpa at itaque ad architecto.
                password: Ipsam vel placeat laborum.
            required:
                - email
                - password
        LoginResponse:
            type: object
            properties:
                email:
                    type: string
                    description: User's email
                    example: Dolorem saepe voluptate veniam incidunt inventore illum.
                id:
                    type: string
                    description: User account's ID
                    example: Sit perferendis sapiente minima.
                refresh_token:
                    type: string
                    description: Refresh token
                    example: Aliquid debitis amet officiis dicta ea.
                role:
                    type: string
                    description: User's role
                    example: Molestiae omnis.
                token:
                    type: string
                    description: JWT Token
                    example: Delectus possimus nam accusamus.
            example:
                email: Nulla sed.
                id: Aliquid provident est illo officiis.
                refresh_token: Voluptatem amet fugit dolores sequi.
                role: Dolorem dolorem et pariatur voluptas.
                token: Minima error ad veniam pariatur qui.
            required:
                - email
                - token
                - refresh_token
                - role
        OperationStatusResponse:
            type: object
            properties:
                message:
                    type: string
                    description: Operation status
                    example: Delectus cumque et et quo.
            example:
                message: Commodi pariatur reiciendis ex possimus eius accusantium.
            required:
                - message
        RefreshTokenRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Quaerat iure quod ut voluptate.
                refreshToken:
                    type: string
                    description: Refresh token
                    example: Quis eligendi ullam quasi enim laudantium aliquam.
            example:
                email: Reiciendis culpa velit optio error.
                refreshToken: Ut velit velit numquam.
            required:
                - email
                - refreshToken
        RegisterRequestBody:
            type: object
            properties:
                confirmedPassword:
                    type: string
                    description: Confirmed password of the user
                    example: Illum placeat autem.
                email:
                    type: string
                    description: User email
                    example: Veritatis suscipit deleniti sit ipsam.
                firstName:
                    type: string
                    description: User first name
                    example: Ipsam commodi ut autem.
                lastName:
                    type: string
                    description: User last name
                    example: Voluptatem qui autem dolorem ipsum.
                password:
                    type: string
                    description: User password
                    example: Est repellendus alias corporis mollitia neque consequuntur.
            example:
                confirmedPassword: Qui beatae deserunt nihil qui recusandae hic.
                email: Ex repellendus.
                firstName: Qui quia.
                lastName: Est repellendus exercitationem aut delectus.
                password: Sapiente nostrum minima reiciendis.
            required:
                - email
                - password
                - confirmedPassword
                - firstName
                - lastName
        UpdateProfileNamesRequestBody:
            type: object
            properties:
                firstName:
                    type: string
                    description: Updated user first name
                    example: Facere temporibus et numquam officia.
                lastName:
                    type: string
                    description: Updated user last name
                    example: Totam velit repudiandae.
            example:
                firstName: Corporis ut magnam dolor quas incidunt.
                lastName: Ex et nesciunt iure non dolor.
            required:
                - firstName
                - lastName
        UserProfileResponse:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Dolores sit sed officiis consequatur.
                firstName:
                    type: string
                    description: First name
                    example: Quia est in aut id accusantium ab.
                friendsList:
                    type: array
                    items:
                        $ref: '#/components/schemas/Friend'
                    description: Friendslist
                    example:
                        - email: Dolorum rerum.
                          firstName: Dolores quibusdam.
                          id: Maxime molestiae.
                          lastName: Labore tempora.
                        - email: Dolorum rerum.
                          firstName: Dolores quibusdam.
                          id: Maxime molestiae.
                          lastName: Labore tempora.
                id:
                    type: string
                    description: User ID
                    example: Doloribus atque accusantium odio natus tenetur.
                lastName:
                    type: string
                    description: Last name
                    example: Doloremque sequi sed.
            example:
                email: Impedit est sapiente quas quia voluptatem.
                firstName: Eos repellat et minima voluptatem.
                friendsList:
                    - email: Dolorum rerum.
                      firstName: Dolores quibusdam.
                      id: Maxime molestiae.
                      lastName: Labore tempora.
                    - email: Dolorum rerum.
                      firstName: Dolores quibusdam.
                      id: Maxime molestiae.
                      lastName: Labore tempora.
                id: Ipsa totam nihil ut.
                lastName: Occaecati asperiores minus impedit sed quis sed.
            required:
                - id
                - email
                - firstName
                - lastName
                - friendsList
tags:
    - name: auth
      description: Authentication service is responsible for handling user data and requests
    - name: info
      description: Application info
    - name: user
      description: User service is responsible for handling user data and requests
